project:
  type: website
  output-dir: docs

website:
  title: "LS6036 Python programming"
  page-navigation: true
  bread-crumbs: false  
  navbar:
      left:
        - text: "Why Python"
          href: index.qmd
        - text: "Set Up"
          href: setup.qmd
        - text: "Learn"
          href: learn.qmd
        - text: "Careers"
          href: careers.qmd
        - text: "CheatSheet"
          href: cheatsheet.qmd
        - text: "Help"
          href: help.qmd
  sidebar:
    - title: "Learn"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - section: "**Python introduction: basics**"
          contents:
            - section: "Python essentials"
              contents:
                - href: learn.qmd
                - href: worksheets/Comments.qmd
                - href: worksheets/Variables.qmd
                - href: worksheets/FormatStrings.qmd
                - href: worksheets/DataTypes.qmd
                - href: worksheets/Maths.qmd
                - href: worksheets/OxygenInBlood.qmd
            -  section: "Inputs, ifs and elses"
               contents:
                 - href: worksheets/UserInput.qmd
                 - href: worksheets/ifelse.qmd
                 - href: worksheets/ifelse_conditions.qmd
                 - href: worksheets/ifelse_fixerrors.qmd
                 - href: worksheets/ifelifelse.qmd
                 - href: worksheets/ifmuseumdiscount.qmd
            -  section: "Lists and dictionaries"
               contents:
                 - href: worksheets/Lists.qmd
                 - href: worksheets/List_index.qmd
                 - href: worksheets/List_slicing.qmd
                 - href: worksheets/List_methods.qmd
                 - href: worksheets/Range.qmd
                 - href: worksheets/Dictionaries.qmd
  favicon: /Logo/LS6036_face.png
    

format:
  live-html:
    theme:
      light: lightly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css

margin-header: |
  ![](/Logo/LS6036_with_text.png)

filters:
  - /Users/lizzie/Documents/Kingston/Year_2526/LS6036/LS6036 Python Course/filters/tools_tabset_python.lua



