project:
  type: website
  output-dir: docs
  resources: 
    - course_files/**

website:
  title: "LS6036 Python programming"
  page-navigation: true
  bread-crumbs: false  
  navbar:
      left:
        - text: "Why Python"
          href: index.qmd
        - text: "Set Up"
          href: setup.qmd
        - text: "Learn"
          href: learn.qmd
        - text: "Careers"
          href: careers.qmd
        - text: "CheatSheet"
          href: cheatsheet.qmd
        - text: "Help, Error!"
          href: help.qmd
  sidebar:
    - title: "Learn"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - section: "**Python introduction: basics**"
          contents:
            - section: "Python essentials"
              contents:
                - href: learn.qmd
                - href: worksheets/Comments.qmd
                - href: worksheets/Variables.qmd
                - href: worksheets/FormatStrings.qmd
                - href: worksheets/DataTypes.qmd
                - href: worksheets/Maths.qmd
                - href: worksheets/OxygenInBlood.qmd
            -  section: "Inputs, ifs and elses"
               contents:
                 - href: worksheets/UserInput.qmd
                 - href: worksheets/UserInput_DataTypes.qmd
                 - href: worksheets/ifelse.qmd
                 - href: worksheets/ifelse_conditions.qmd
                 - href: worksheets/ifelse_fixerrors.qmd
                 - href: worksheets/ifelifelse.qmd
                 - href: worksheets/ifmuseumdiscount.qmd
            -  section: "Lists and dictionaries"
               contents:
                 - href: worksheets/Lists.qmd
                 - href: worksheets/List_index.qmd
                 - href: worksheets/List_slicing.qmd
                 - href: worksheets/List_methods.qmd
                 - href: worksheets/Dictionaries.qmd
                 - href: worksheets/Dictionaries_II.qmd
                 - href: worksheets/nested_lists_and_dictionaries.qmd
                 - href: worksheets/Species_ages.qmd
        - section: "**Logic and Loops**"
          contents:
            - section: "Logic"
              contents: 
                - href: worksheets/Logic.qmd
                - href: worksheets/String_methods.qmd
                - href: worksheets/Adding_number_string.qmd 
                - href: worksheets/random.qmd
            - section: "for loops"
              contents:
                 - href: worksheets/forloops.qmd
                 - href: worksheets/Range.qmd
                 - href: worksheets/for_iterables.qmd
                 - href: worksheets/forloop_practice.qmd
                 - href: worksheets/FizzBuzz.qmd
            - section: "while loops"
              contents:
                 - href: worksheets/while_loop.qmd
                 - href: worksheets/whileloop_neverending.qmd
                 - href: worksheets/while_practice.qmd
            - section: "Reading from a file"
              contents:
                 - href: worksheets/reading_from_a_file.qmd
                 - href: worksheets/writing_to_a_file.qmd
                 - href: worksheets/reading_a_fasta_file.qmd
                 - href: worksheets/premature_stop_codon.qmd
        - section: "**Matplotlib**"
          contents:
            - section: "Plotting graphs"
              contents: 
                  - href: worksheets/matplotlib_intro.qmd
                  - href: worksheets/matplotlib_scatter.qmd
                  - href: worksheets/matplotlib_barchart.qmd
                  - href: worksheets/matplotlib_piechart.qmd
                  - href: worksheets/matplotlib_boxplot.qmd
                  - href: worksheets/matplotlib_practice.qmd
            - section: "Styling graphs"
              contents: 
                  - href: worksheets/matplotlib_colors.qmd
                  - href: worksheets/matplotlib_linestyle.qmd
                  - href: worksheets/matplotlib_markers.qmd
                  - href: worksheets/matplotlib_titles.qmd
                  - href: worksheets/matplotlib_legend.qmd
                  - href: worksheets/matplotlib_xyticks.qmd
                  - href: worksheets/matplotlib_xy_limits.qmd
            - section: "Plotting from a CSV file"
              contents: 
                  - href: worksheets/reading_a_csv_file.qmd
                  - href: worksheets/plotting_from_a_csv_file.qmd 
                  - href: worksheets/crab_activity.qmd
                  

  favicon: /Logo/LS6036_face.png
    

format:
  live-html:
    theme:
      light: 
        - lightly
      dark: 
        - darkly
    respect-user-color-scheme: true
    css: styles.css

engine: jupyter
lightbox: true

margin-header: |
  ![](/Logo/Logo_with_diya_and_text.png)

filters:
  - /Users/lizzie/Documents/Kingston/Year_2526/LS6036/LS6036 Python Course/filters/tools_tabset_python.lua