# FizzBuzz Activity

This is a classic question for learning programming. 

Please write a program that prints the numbers from 1 to 100. But:
-   for the multiples of three print the word ”Fizz” instead of the number
-   for the multiples of five print the word ”Buzz” instead of the number
-   for numbers that are multiples of both three and five, print the word ”FizzBuzz”.

::: { .callout-note collapse="true" title="Show output"}

The output should look like this: 

```{python}
#| echo: false
for i in range(1,100):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)
```

::: 

::: { .callout-tip collapse="true" title="Hint 1"}
When writing this, do one step at a time and test your code: 

1.  Just print all the numbers from 1 to 100 
2.  Change the numbers divisible by 3 to "Fizz"
3.  Change the numbers divisible by 5 to "Buzz"
4.  Change the numbers divisible by 3 **and** 5 to "FizzBuzz"

One way of calculating if a number can be divided by 3 is using the **modulus** `%` which gives you the remainder after division. 
_If a number is divisible by 3, when you divide by three what is the remainder?_
:::

::: { .callout-tip collapse="true" title="Hint 2"}
You'll need to use a range of different skills here:

1. A for loop, to go from 1 to 100 
2. If/elif/else statements to determine if each number if divisible by 3 or 5 
3. The maths modulus sign `%` or ranges with a step. 

:::

::: { .callout-tip collapse="true" title="Hint 3"}
You need to make sure your if statements are in the right order - else you may never get a FizzBuzz. 

Drawing a flow chart can help you plan your answer!
:::
