# Oxygen in blood exercise 

A patient has the following blood oxygen readings: 

| Type | Measurement | Units | 
| --- | --- | --- | 
| Haemoglobin concentration | 15 | g / dL blood | 
| Haemoglobin saturation | 96 | % | 
| Arterial oxygen tension | 89 | mmHg |

: Patient 1 haemoglobin measurements {.striped .hover}

## Calculate bound oxygen 

Every gram of hemoglobin can maximally bind **1.34 mL** of oxygen. 

This mean we can calculate the maximum amount of oxygen bound to haemoglobin by multiplying the **concentration of haemoglobin** ```[Hb]``` (in g / dL blood) with this value 1.34 mL O_2 per g haemoglobin. 

However, not all haemoglobin in the blood is bound to oxygen. We can multiply the maximum amount of oxygen bound to haemoglobin by the haemoglobin saturation to calculate the amount of oxygen bound in the blood. 

$$
\text{Bound oxygen} = [Hb] \frac{\text{g Hb}}{\text{dL}} \times 1.34 \frac {\text{mL } O_2}{\text{g Hb}} \times \frac{\text{Hb saturation}}{100}
$$

### Give it a go: 

```{pyodide}
#| exercise: ex_1
Hb_concentration = ______
Hb_saturation = ______
Max_oxygen_per_Hb = ______ 

Bound_oxygen = _______
print(Bound_oxygen)
```

::: { .callout-tip collapse="true" title="Show answer"}
```{python}
Hb_concentration = 15
Hb_saturation = 96
Max_oxygen_per_Hb = 1.34 

Bound_oxygen = Hb_concentration * Hb_saturation * Max_oxygen_per_Hb
print(Bound_oxygen)
```
:::

## Calculate dissolved oxygen 

There is also a small amount of oxygen dissolved in the blood, not bound to haemoglobin. 

We can calculate this by multiplying the arterial oxygen tension (in mmHg) and the solubility coefficient of oxygen. 

The solubility coefficient of oxygen is $0.0031 \text{mL} \frac{\frac{O_2}{\text{dL blood}}}{\text{mmHg}}$. 

$$
\text{Dissolved oxygen} = \text{arterial oxygen tension mmHg} \times 0.0031 \text{mL} \frac{\frac{O_2}{\text{dL blood}}}{\text{mmHg}}
$$

### Give it a go

```{pyodide}
#| exercise: ex_2
arterial_tension = ______
solubility_coefficient = ______

Dissolved_oxygen = _______
print(Dissolved_oxygen)
```

::: { .callout-tip collapse="true" title="Show answer"}
```{python}
arterial_tension = 89
solubility_coefficient = 0.0031

Dissolved_oxygen = arterial_tension * solubility_coefficient
print(Dissolved_oxygen)
```
:::

## Calculate total oxygen

Now to calculate the total oxygen, all you need to do is combine the two and add them together! 

::: { .callout-tip collapse="true" title="Show answer"}
```{python}
Hb_concentration = 15
Hb_saturation = 96
Max_oxygen_per_Hb = 1.34 

Bound_oxygen = Hb_concentration * Hb_saturation * Max_oxygen_per_Hb
print(Bound_oxygen)

arterial_tension = 89
solubility_coefficient = 0.0031

Dissolved_oxygen = arterial_tension * solubility_coefficient
print(Dissolved_oxygen)

Total_oxygen = Bound_oxygen + Dissolved_oxygen 
print(Total_oxygen)
```
:::

Now if we have a second patient with different readings - how quickly can you calculate the total blood oxygen? 

| Type | Measurement | Units | 
| --- | --- | --- | 
| Haemoglobin concentration | 12 | g / dL blood | 
| Haemoglobin saturation | 94 | % | 
| Arterial oxygen tension | 76 | mmHg |

: Patient 2 haemoglobin measurements {.striped .hover}