# Input data types

When you use a function like `input()`, python doesn't know if you're going to enter: 
  
-  a string (a word or mix of letters and numbers, `str`)
-  a whole number (integer, `int`)
-  a number with decimal points (floating point number, `float`)

To get around this - it assumes the input is **always** treated as a string (or word) 

Try the below example - it doesn't behave how you might expect! 

```{python}
#| eval: false
# Calculate users age in 10 years
user_age = input("What is your age? ")
double_age = user_age * 2
print("Double your age is ", double_age)
```

This is the result for a user who is 19 years old: 

```{python}
#| echo: false
# Calculate users age in 10 years
user_age = "19"
double_age = user_age * 2
print("Double your age is ", double_age)
```

Now that's not quite what we want! So we need to **convert** the string (word) to a whole number (integer). To do this, we can use the `int()` function. 

```{python}
#| eval: false
# Calculate users age in 10 years
user_age = input("What is your age? ")
# Use int() to convert the input to a number
# Overwrite user_age variable with the result from int(user_age)
user_age = int(user_age) 
double_age = user_age * 2
print("Double your age is ", double_age)
```

Now that is giving the answer we actually wanted! 

Examples of different functions to use data types is found below:

| Conversion | Function | Example | 
| -- | -- | -- | 
| To integer | `int()` | `user_age = int(user_age)` | 
| To floating point number | `float()` | `weight = float(weight)` | 
| To string | `str()` | `age_as_word = str(user_age)` | 

## Give it a go: 

Write a python program which: 

1.  Asks the user which year they were born 
2.  Calculates how old they will be in the year 3000 
3.  Prints this information back to the user 

::: { .callout-tip collapse="true" title="Show answer"}
```{python}
#| eval: false 
# Get user birth year using input()
user_birth_year = input("What year were you born?")

# Convert birth year to integer
user_birth_year = int(user_birth_year)

# Calculate age in the Year 3000
user_year_3000_age = 3000 - user_birth_year 

# Print result
print("In the year 3000 you will be: ", user_year_3000_age)
```
:::


