---
config:
  theme: mc
  look: neo
---
flowchart TD
    B{"Is a dog person?"}
    B -- True --> C["Dog person"]
    D{"Is a cat person?"}
    D -- True --> E["Cat person"]
    D -- False --> H["Not a dog or cat or bird person"]
